// Code generated by Slice Machine. DO NOT EDIT.

import Broadcast from "./Broadcast/index.svelte";
import Intro from "./Intro/index.svelte";
import MyClients from "./MyClients/index.svelte";
import MyWork from "./MyWork/index.svelte";

export const components = {
  broadcast: Broadcast,
  intro: Intro,
  my_clients: MyClients,
  my_work: MyWork,
};
