// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | IntroSlice
  | MyClientsSlice
  | BroadcastSlice
  | MyWorkSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *Broadcast → Primary*
 */
export interface BroadcastSliceDefaultPrimary {
  /**
   * broadcast field in *Broadcast → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: broadcast.primary.broadcast
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  broadcast: prismic.KeyTextField;
}

/**
 * Default variation for Broadcast Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BroadcastSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BroadcastSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Broadcast*
 */
type BroadcastSliceVariation = BroadcastSliceDefault;

/**
 * Broadcast Shared Slice
 *
 * - **API ID**: `broadcast`
 * - **Description**: Broadcast
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BroadcastSlice = prismic.SharedSlice<
  "broadcast",
  BroadcastSliceVariation
>;

/**
 * Primary content in *Intro → Primary*
 */
export interface IntroSliceDefaultPrimary {
  /**
   * avatar field in *Intro → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.primary.avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * title field in *Intro → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Intro → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * subtext field in *Intro → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.primary.subtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext: prismic.KeyTextField;
}

/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Intro*
 */
type IntroSliceVariation = IntroSliceDefault;

/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: Intro
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSlice = prismic.SharedSlice<"intro", IntroSliceVariation>;

/**
 * Primary content in *MyClients → Primary*
 */
export interface MyClientsSliceDefaultPrimary {
  /**
   * title field in *MyClients → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: my_clients.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * clients field in *MyClients → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: my_clients.primary.clients
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  clients: prismic.ImageField<never>;
}

/**
 * Default variation for MyClients Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MyClientsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MyClientsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MyClients*
 */
type MyClientsSliceVariation = MyClientsSliceDefault;

/**
 * MyClients Shared Slice
 *
 * - **API ID**: `my_clients`
 * - **Description**: MyClients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MyClientsSlice = prismic.SharedSlice<
  "my_clients",
  MyClientsSliceVariation
>;

/**
 * Primary content in *MyWork → Primary*
 */
export interface MyWorkSliceDefaultPrimary {
  /**
   * title field in *MyWork → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: my_work.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * website1 field in *MyWork → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: my_work.primary.website1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  website1: prismic.ImageField<never>;
}

/**
 * Default variation for MyWork Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MyWorkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MyWorkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MyWork*
 */
type MyWorkSliceVariation = MyWorkSliceDefault;

/**
 * MyWork Shared Slice
 *
 * - **API ID**: `my_work`
 * - **Description**: MyWork
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MyWorkSlice = prismic.SharedSlice<"my_work", MyWorkSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BroadcastSlice,
      BroadcastSliceDefaultPrimary,
      BroadcastSliceVariation,
      BroadcastSliceDefault,
      IntroSlice,
      IntroSliceDefaultPrimary,
      IntroSliceVariation,
      IntroSliceDefault,
      MyClientsSlice,
      MyClientsSliceDefaultPrimary,
      MyClientsSliceVariation,
      MyClientsSliceDefault,
      MyWorkSlice,
      MyWorkSliceDefaultPrimary,
      MyWorkSliceVariation,
      MyWorkSliceDefault,
    };
  }
}
